---
- name: Add PostgreSQL 10 repo
  yum: 
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present

- name: PostgreSQL 10 install
  yum:
    name: ['postgresql10-server', 'expect-devel']
    state: latest

- name: Init database and create user for Zabbix
  ansible.builtin.shell: /usr/pgsql-10/bin/postgresql-10-setup initdb
  
- name: Start service postgresql-10
  ansible.builtin.service:
    name: postgresql-10
    state: started
    enable: yes

- name: Init database and create user for Zabbix
  ansible.builtin.shell: |
    sudo -u postgres /usr/pgsql-10/bin/createuser --pwprompt zabbix
    expect "Enter password for new role:"
    send "{{ zabbix_password }}\n"
    expect "\nEnter it again:"
    send "{{ zabbix_password }}\n"

    sudo -u postgres createdb -O zabbix zabbix
    exit 0
  args:
    executable: /usr/bin/expect
  delegate_to: localhost

- name: Init database and create user for Zabbix
  ansible.builtin.shell: echo "host    all             zabbix          127.0.0.1/32            trust" >> /var/lib/pgsql/10/data/pg_hba.conf
