---
- name: Install Zabbix repo
  yum:
    name: https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
    state: present

- name: Yum clean all
  ansible.builtin.shell: yum clean all

- name: Agent install
  yum:
    name: ['zabbix-agent']
    state: present
    
- name: Copy standart agent config file 
  ansible.builtin.copy:
    src: /roles/zabbix50agent/templates/zabbix_agentd.conf
    dest: /etc/zabbix/zabbix_agentd.conf
    
- firewalld:
    port: ['80/tcp', '443/tcp', '10050/tcp', '10051/tcp']
    permanent: true
    state: enabled