---
- name: "Debian 10"
  hosts: 127.0.0.1
  connect: local
  var_files: /root/zabbix5forcentos7/group_vars/debian10server
  become:
    true
  become_method:
    sudo
  become_user:
    root
  roles:
   - debian10server 
