---
- name: "CentOS"
  hosts: 127.0.0.1
  connection: local
  vars_files:
   - "{{ gitclonepath }}/group_vars/centos7"
  become:
    true
  become_method:
    sudo
  become_user:
    root
  roles:
   - zabbix50server