---
- name: "Ubuntu 18"
  hosts: 127.0.0.1
  connection: local
  vars_files: /root/zabbix5forcentos7/group_vars/ubuntu18server
  become:
    true
  become_method:
    sudo
  become_user:
    root
  roles:
   - ubuntu18server

