---
- name: Zabbix repo install 1
  zypper:
    name: https://repo.zabbix.com/zabbix/5.2/sles/15/x86_64/zabbix-release-5.2-1.sles15.noarch.rpm
    state: present
    
- name: Zabbix repo install 2
  ansible.builtin.shell: zypper --gpg-auto-import-keys refresh 'Zabbix Official Repository'
  
- name: Activate Web and Scripting Module
  ansible.builtin.shell: SUSEConnect -p sle-module-web-scripting/15/x86_64
  
- name: Install server,frontend,agent
  zypper:
    name: ['zabbix-agent']
    state: present
    
- name: Copy standart agent config file 
  ansible.builtin.copy:
    src: "{{ gitclonepath }}/roles/zabbix50agent/templates/zabbix_agentd.conf"
    dest: /etc/zabbix/zabbix_agentd.conf
    
- name: Restart service zabbix-agent
  ansible.builtin.service:
    name: zabbix-agent
    state: restarted
    enabled: yes