---
- name: Install Zabbix repo
  shell: "wget {{ repo_url }} && dpkg -i {{ repo_file }} && apt update"

- name: Server and Agent install
  apt:
    name: ['zabbix-server-pgsql', 'zabbix-frontend-php', 'php7.4-pgsql', 'zabbix-nginx-conf', 'zabbix-agent']
    state: present

- name: Copy DB config file
  ansible.builtin.copy:
    src: "{{ gitclonepath }}/roles/ubuntu20server/templates/zabbix/zabbix_server.conf"
    dest: /etc/zabbix/zabbix_server.conf 

- name: Copy Nginx config file 
  ansible.builtin.copy:
    src: "{{ gitclonepath }}/roles/ubuntu20server/templates/nginx/zabbix.conf"
    dest: /etc/zabbix/nginx.conf 

- name: Copy PHP config file 
  ansible.builtin.copy:
    src: "{{ gitclonepath }}/roles/ubuntu20server/templates/php/zabbix.conf"
    dest: /etc/zabbix/php-fpm.conf

- name: Restart all services
  shell: "systemctl restart zabbix-server zabbix-agent nginx php7.4-fpm"

- name: Enable all service
  shell: "systemctl enable zabbix-server zabbix-agent nginx php7.4-fpm"
    




