---
- name: Install Zabbix repo
  ansible.builtin.shell: wget https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1+focal_all.deb && dpkg -i zabbix-release_5.0-1+focal_all.deb && apt update

- name: Server and Agent install
  apt:
    name: ['zabbix-server-pgsql', 'zabbix-frontend-php', 'php7.4-pgsql', 'zabbix-nginx-conf', 'zabbix-agent']
    state: present

- name: Copy DB config file
  ansible.builtin.copy:
    src: "{{ gitclonepath }}/roles/zabbix50server/templates/zabbix/zabbix_server.conf"
    dest: /etc/zabbix/zabbix_server.conf 

- name: Copy Nginx config file 
  ansible.builtin.copy:
    src: "{{ gitclonepath }}/roles/zabbix50server/templates/nginx/zabbix.conf"
    dest: /etc/zabbix/nginx.conf 

- name: Copy PHP config file 
  ansible.builtin.copy:
    src: "{{ gitclonepath }}/roles/zabbix50server/templates/php/zabbix.conf"
    dest: /etc/zabbix/php-fpm.conf

- name: Restart service zabbix-server
  ansible.builtin.service:
    name: zabbix-server
    state: restarted
    enabled: yes

- name: Restart service zabbix-agent
  ansible.builtin.service:
    name: zabbix-agent
    state: restarted
    enabled: yes

- name: Restart service nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes

- name: Restart service php7.4-fpm
  ansible.builtin.service:
    name: php7.4-fpm
    state: restarted
    enabled: yes
    




