---
- name: Install Zabbix repo
  yum:
    name: "{{ repo_url }}"
    state: present

- name: Yum clean all
  ansible.builtin.shell: yum clean all

- name: Agent install
  yum:
    name: ['zabbix-agent']
    state: present
    
- name: Copy standart agent config file 
  ansible.builtin.copy:
    src: "{{ gitclonepath }}/roles/zabbix50agent/templates/zabbix_agentd.conf"
    dest: /etc/zabbix/zabbix_agentd.conf
    
- name: Restart service zabbix-agent
  ansible.builtin.service:
    name: zabbix-agent
    state: restarted
    enabled: yes