---
- name: Zabbix repo install 1
  zypper:
    name: https://repo.zabbix.com/zabbix/5.2/sles/15/x86_64/zabbix-release-5.2-1.sles15.noarch.rpm
    state: present
    
- name: Zabbix repo install 2
  ansible.builtin.shell: zypper --gpg-auto-import-keys refresh 'Zabbix Official Repository'
  
- name: Activate Web and Scripting Module
  ansible.builtin.shell: SUSEConnect -p sle-module-web-scripting/15/x86_64
  
- name: Install server,frontend,agent
  zypper:
    name: ['zabbix-server-pgsql', 'zabbix-web-pgsql', 'zabbix-nginx-conf', 'zabbix-agent']
    state: present

- name: Copy DB config file
  ansible.builtin.copy:
    src: "{{ gitclonepath }}/roles/zabbix50server/templates/zabbix/zabbix_server.conf"
    dest: /etc/zabbix/zabbix_server.conf 

- name: Copy Nginx config file 
  ansible.builtin.copy:
    src: "{{ gitclonepath }}/roles/zabbix50server/templates/nginx/zabbix.conf"
    dest: /etc/nginx/conf.d/zabbix.conf 

- name: Copy PHP config file 
  ansible.builtin.copy:
    src: "{{ gitclonepath }}/roles/zabbix50server/templates/php/zabbix.conf"
    dest: /etc/php7/fpm/php-fpm.conf.default

- name: Restart service zabbix-server
  ansible.builtin.service:
    name: zabbix-server
    state: restarted
    enabled: yes

- name: Restart service zabbix-agent
  ansible.builtin.service:
    name: zabbix-agent
    state: restarted
    enabled: yes

- name: Restart service nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes

- name: Restart service php-fpm
  ansible.builtin.service:
    name: php-fpm
    state: restarted
    enabled: yes