---
- name: Install Zabbix repo
  yum:
    name: https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
    state: present

- name: Yum clean all
  ansible.builtin.shell: yum clean all

- name: Server and Agent install
  yum:
    name: ['zabbix-server-pgsql', 'zabbix-agent', 'centos-release-scl']
    state: present

- name: Copy repo file for frontend
  ansible.builtin.copy:
    src: ~/zabbix5forcentos7/roles/zabbix50server/templates/yumrepos/zabbix.repo
    dest: /etc/yum.repos.d/zabbix.repo

- name: Web-interface for Zabbix install
  yum:  
    name: ['zabbix-web-pgsql-scl', 'zabbix-nginx-conf-scl']
    state: present

- name: Copy DB config file
  ansible.builtin.copy:
    src: ~/zabbix5forcentos7/roles/zabbix50server/templates/zabbix/zabbix_server.conf
    dest: /etc/zabbix/zabbix_server.conf 

- name: Copy Nginx config file 
  ansible.builtin.copy:
    src: ~/zabbix5forcentos7/roles/zabbix50server/templates/nginx/zabbix.conf
    dest: /etc/opt/rh/rh-nginx116/nginx/conf.d/zabbix.conf 

- name: Copy PHP config file 
  ansible.builtin.copy:
    src: ~/zabbix5forcentos7/roles/zabbix50server/templates/php/zabbix.conf
    dest: /etc/opt/rh/rh-php72/php-fpm.d/zabbix.conf
    
- name: Restart service zabbix-server
  ansible.builtin.service:
    name: zabbix-server
    state: restarted
    enabled: yes

- name: Restart service zabbix-agent
  ansible.builtin.service:
    name: zabbix-agent
    state: restarted
    enabled: yes

- name: Restart service rh-nginx116-nginx
  ansible.builtin.service:
    name: rh-nginx116-nginx
    state: restarted
    enabled: yes

- name: Restart service rh-php72-php-fpm
  ansible.builtin.service:
    name: rh-php72-php-fpm
    state: restarted
    enabled: yes
    




