---
- name: Zabbix repo install 1
  zypper:
    name: https://repo.zabbix.com/zabbix/5.0/sles/12/x86_64/zabbix-release-5.0-1.el12.noarch.rpm
    state: present
    
- name: Zabbix repo install 2
  ansible.builtin.shell: zypper --gpg-auto-import-keys refresh 'Zabbix Official Repository'
  
- name: Activate Web and Scripting Module
  ansible.builtin.shell: SUSEConnect -p sle-module-web-scripting/12/x86_64
  
- name: Install nginx repository
  ansible.builtin.shell: zypper addrepo -G -t yum -c 'https://nginx.org/packages/sles/12' nginx
  
- name: Install server,frontend,agent
  zypper:
    name: ['zabbix-agent']
    state: present 
    
- name: Restart service zabbix-agent
  ansible.builtin.service:
    name: zabbix-agent
    state: restarted
    enabled: yes
