---
- name: Install python-dnf
  ansible.buildin.shell: dnf install python2-dnf -y
  
- name: Install Zabbix repo
  ansible.buildin.dnf:
    name: "{{ repo_url }}"
    state: present

- name: Yum clean all
  ansible.builtin.shell: yum clean all

- name: Server and Agent install
  ansible.buildin.dnf:
    name: ['zabbix-server-pgsql', 'zabbix-agent', 'zabbix-web-pgsql', 'zabbix-nginx-conf']
    state: present

- name: Copy DB config file
  ansible.builtin.copy:
    src: "{{ gitclonepath }}/roles/zabbix50server/templates/zabbix/zabbix_server.conf"
    dest: /etc/zabbix/zabbix_server.conf 

- name: Copy Nginx config file 
  ansible.builtin.copy:
    src: "{{ gitclonepath }}/roles/zabbix50server/templates/nginx/zabbix.conf"
    dest: /etc/nginx/conf.d/zabbix.conf 

- name: Copy PHP config file 
  ansible.builtin.copy:
    src: "{{ gitclonepath }}/roles/zabbix50server/templates/php/zabbix.conf"
    dest: /etc/php-fpm.d/zabbix.conf

- name: Restart service zabbix-server
  ansible.builtin.service:
    name: zabbix-server
    state: restarted
    enabled: yes

- name: Restart service zabbix-agent
  ansible.builtin.service:
    name: zabbix-agent
    state: restarted
    enabled: yes

- name: Restart service nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes

- name: Restart service php-fpm
  ansible.builtin.service:
    name: php-fpm
    state: restarted
    enabled: yes
    




